# NumPy

In [ ]:
import numpy as np

In [13]:
myarr=np.array([[3,6,9,12]], np.int8)

In [16]:
myarr[0,2]

np.int8(9)

In [17]:
myarr.dtype

dtype('int8')

# Array Creation: Conversion from other Python Structures  

In [23]:
listArray=np.array([[1,2,3],[3,2,1],[2,1,3]])

In [24]:
listArray

array([[1, 2, 3],
       [3, 2, 1],
       [2, 1, 3]])

In [25]:
listArray.dtype

dtype('int64')

In [26]:
listArray.shape

(3, 3)

In [28]:
listArray.size

9

In [32]:
zero=np.zeros((3,7))

In [33]:
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [34]:
zero.dtype

dtype('float64')

In [37]:
rng=np.arange(15)

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
lspace=np.linspace(1,50,12)

In [42]:
lspace

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [47]:
emp=np.empty((4,6))

In [48]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521103e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.11261162e-306, 8.34443015e-308, 2.22507386e-306]])

In [49]:
ide=np.identity(45)

In [50]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
ide.shape

(45, 45)

In [54]:
arr=np.arange(99)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [61]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [62]:
arr.ravel()  #converts into 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [64]:
ar=np.array(x)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
ar.sum(axis=0) #sum of column 

array([12,  8,  9])

In [68]:
ar.sum(axis=1) #sum of row

array([ 6, 15,  8])

In [71]:
ar.T  # transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [72]:
ar.flat

In [73]:
for item in ar.flat:
    print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29

In [74]:
for item in ar.flat:
    print(item)


1
2
3
4
5
6
7
1
0


In [75]:
ar.ndim

2

In [76]:
ar.size

9

In [77]:
ar.nbytes  #total bytes consumed

72

In [81]:
one=np.array([69,21,88,31])

In [83]:
one.argmax()

np.int64(2)

In [84]:
one.argmin()

np.int64(1)

In [93]:
one.argsort()

array([1, 3, 0, 2])

In [95]:
ar1=np.array([[1,2,3],[3,2,1],[2,3,1]])

In [96]:
ar2=np.array([[1,1,1],[2,2,2],[3,3,3]])

In [97]:
ar1+ar2

array([[2, 3, 4],
       [5, 4, 3],
       [5, 6, 4]])

In [98]:
ar1*ar2

array([[1, 2, 3],
       [6, 4, 2],
       [6, 9, 3]])

In [99]:
ar1*ar2.T

array([[1, 4, 9],
       [3, 4, 3],
       [2, 6, 3]])

In [100]:
ar1^ar2

array([[0, 3, 2],
       [1, 0, 3],
       [1, 0, 2]])

In [108]:
mul=ar1*ar2*ar1

In [109]:
np.sqrt(mul)

array([[1.        , 2.        , 3.        ],
       [4.24264069, 2.82842712, 1.41421356],
       [3.46410162, 5.19615242, 1.73205081]])

In [111]:
ar.sum()

np.int64(29)

In [112]:
ar.min()

np.int64(0)

In [113]:
ar.max()

np.int64(7)

In [114]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [115]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [116]:
 type(ar)

numpy.ndarray

In [118]:
np.count_nonzero(ar)

8

In [119]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))